//connect to the stock market API using Golang
//2019-03-16 Topic Note Team

package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
)

//JSON-to-Go: https://mholt.github.io/json-to-go/ のJSONにAPIから返ってきたStringを入力して、作成。
type AutoGenerated struct {
	Quotes []struct {
		High             string `json:"high"`
		Open             string `json:"open"`
		Bid              string `json:"bid"`
		CurrencyPairCode string `json:"currencyPairCode"`
		Ask              string `json:"ask"`
		Low              string `json:"low"`
	} `json:"quotes"`
}

func main() {
	res, err := http.Get("https://www.gaitameonline.com/rateaj/getrate")
	if err != nil {
		fmt.Println(err)
		return
	}

	defer res.Body.Close()
	execute(res)
}

func execute(res *http.Response) {
	body, err := ioutil.ReadAll(res.Body)
	if err != nil {
		fmt.Println(err)
		return
	}
	// fmt.Println(string(body))

	//JSON をパース
	jsonBytes := ([]byte)(string(body))
	data := new(AutoGenerated)
	if err := json.Unmarshal(jsonBytes, data); err != nil {
		fmt.Println("JSON Unmarshal error:", err)
		return
	}
	fmt.Println(data)
}
